//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omeddle.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Omeddle.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Omegle&quot; is property of Omegle.com. This is not an official Omegle app.
        ///Omeddle code © 2014 Andrew D&apos;Angelo
        ///Thanks to cryzed for OmeglePCL base and Borhan for proxy server!.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about omeddle.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new.
        /// </summary>
        public static string AddNewText {
            get {
                return ResourceManager.GetString("AddNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer question.
        /// </summary>
        public static string AnswerQuestionText {
            get {
                return ResourceManager.GetString("AnswerQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to topics.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMEDDLE.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ask question.
        /// </summary>
        public static string AskQuestionText {
            get {
                return ResourceManager.GetString("AskQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The auto-solving failed. This happens about 10% of the time. Naturally, you will not lose auto-solving credit for this. You can request another auto-solve, or try again manually..
        /// </summary>
        public static string AutoSolveFailedText {
            get {
                return ResourceManager.GetString("AutoSolveFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Solve ({0} remaining).
        /// </summary>
        public static string AutoSolveText {
            get {
                return ResourceManager.GetString("AutoSolveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changed.
        /// </summary>
        public static string ChangedText {
            get {
                return ResourceManager.GetString("ChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chat.
        /// </summary>
        public static string ChatModeText {
            get {
                return ResourceManager.GetString("ChatModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        public static string ClearText {
            get {
                return ResourceManager.GetString("ClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really disconnect?.
        /// </summary>
        public static string ConfirmPrompt {
            get {
                return ResourceManager.GetString("ConfirmPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Exit.
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stranger {0} connected!.
        /// </summary>
        public static string ConnectedText {
            get {
                return ResourceManager.GetString("ConnectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Stranger {0} .
        /// </summary>
        public static string ConnectingText {
            get {
                return ResourceManager.GetString("ConnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error communicating with Omegle server!.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy url.
        /// </summary>
        public static string CopyImageText {
            get {
                return ResourceManager.GetString("CopyImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string CopyText {
            get {
                return ResourceManager.GetString("CopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all images?.
        /// </summary>
        public static string DeleteAllImagesConfirmation {
            get {
                return ResourceManager.GetString("DeleteAllImagesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete all images.
        /// </summary>
        public static string DeleteAllImagesText {
            get {
                return ResourceManager.GetString("DeleteAllImagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string DeletingText {
            get {
                return ResourceManager.GetString("DeletingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stranger {0} disconnected .
        /// </summary>
        public static string DisconnectedText {
            get {
                return ResourceManager.GetString("DisconnectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to examples.
        /// </summary>
        public static string ExampleText {
            get {
                return ResourceManager.GetString("ExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question to discuss:
        ///{0}.
        /// </summary>
        public static string GotQuestionText {
            get {
                return ResourceManager.GetString("GotQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting image!.
        /// </summary>
        public static string ImageDeleteErrorText {
            get {
                return ResourceManager.GetString("ImageDeleteErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0da5b04361f8438.
        /// </summary>
        public static string ImgurApiKey {
            get {
                return ResourceManager.GetString("ImgurApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert previous image link.
        /// </summary>
        public static string InsertImageText {
            get {
                return ResourceManager.GetString("InsertImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intercept list.
        /// </summary>
        public static string InterceptListText {
            get {
                return ResourceManager.GetString("InterceptListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intercept.
        /// </summary>
        public static string InterceptModeText {
            get {
                return ResourceManager.GetString("InterceptModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use live tile.
        /// </summary>
        public static string LiveTileText {
            get {
                return ResourceManager.GetString("LiveTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chatlogs.
        /// </summary>
        public static string LogPageText {
            get {
                return ResourceManager.GetString("LogPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mode select.
        /// </summary>
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messages.
        /// </summary>
        public static string MessageCountText {
            get {
                return ResourceManager.GetString("MessageCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Chat.
        /// </summary>
        public static string NewChatText {
            get {
                return ResourceManager.GetString("NewChatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll need to enter and/or enable at least one question before entering Ask mode!.
        /// </summary>
        public static string NoQuestionsError {
            get {
                return ResourceManager.GetString("NoQuestionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string OpenText {
            get {
                return ResourceManager.GetString("OpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to questions.
        /// </summary>
        public static string QuestionListText {
            get {
                return ResourceManager.GetString("QuestionListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to question.
        /// </summary>
        public static string QuestionModeText {
            get {
                return ResourceManager.GetString("QuestionModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha required.
        /// </summary>
        public static string RecaptchaRequiredText {
            get {
                return ResourceManager.GetString("RecaptchaRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recent.
        /// </summary>
        public static string RecentText {
            get {
                return ResourceManager.GetString("RecentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put a word to find in the first box and the text to replace the mached word in the second.
        ///You can also try using regexes to match text. For example, &quot;(\d+)&quot; matches any number, which is useful for changing ages..
        /// </summary>
        public static string RegexExampleText {
            get {
                return ResourceManager.GetString("RegexExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string RetryText {
            get {
                return ResourceManager.GetString("RetryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved.
        /// </summary>
        public static string SavedText {
            get {
                return ResourceManager.GetString("SavedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send feedback.
        /// </summary>
        public static string SendFeedbackText {
            get {
                return ResourceManager.GetString("SendFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send photo.
        /// </summary>
        public static string SendPhotoText {
            get {
                return ResourceManager.GetString("SendPhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendText {
            get {
                return ResourceManager.GetString("SendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send to {0}.
        /// </summary>
        public static string SendToText {
            get {
                return ResourceManager.GetString("SendToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgur image management....
        /// </summary>
        public static string SharedImagesText {
            get {
                return ResourceManager.GetString("SharedImagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when trying to share your chat.
        /// </summary>
        public static string ShareErrorText {
            get {
                return ResourceManager.GetString("ShareErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share from library.
        /// </summary>
        public static string ShareFromLibraryText {
            get {
                return ResourceManager.GetString("ShareFromLibraryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out this chat from Omeddle!.
        /// </summary>
        public static string ShareLinkText {
            get {
                return ResourceManager.GetString("ShareLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share chat.
        /// </summary>
        public static string ShareText {
            get {
                return ResourceManager.GetString("ShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omeddle Chat on {0} at {1}.
        /// </summary>
        public static string ShareTitleFormatText {
            get {
                return ResourceManager.GetString("ShareTitleFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strangers connected!.
        /// </summary>
        public static string StrangersConnectedText {
            get {
                return ResourceManager.GetString("StrangersConnectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to strangers.
        /// </summary>
        public static string StrangersConnectingText {
            get {
                return ResourceManager.GetString("StrangersConnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stranger {0}.
        /// </summary>
        public static string StrangerText {
            get {
                return ResourceManager.GetString("StrangerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitText {
            get {
                return ResourceManager.GetString("SubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SystemText {
            get {
                return ResourceManager.GetString("SystemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take photo.
        /// </summary>
        public static string TakePhotoText {
            get {
                return ResourceManager.GetString("TakePhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terminate.
        /// </summary>
        public static string TerminateText {
            get {
                return ResourceManager.GetString("TerminateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to topics.
        /// </summary>
        public static string TopicPageTitle {
            get {
                return ResourceManager.GetString("TopicPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stranger {0} is typing .
        /// </summary>
        public static string TypingText {
            get {
                return ResourceManager.GetString("TypingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh live tile.
        /// </summary>
        public static string UpdateLiveTileText {
            get {
                return ResourceManager.GetString("UpdateLiveTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading data .
        /// </summary>
        public static string UploadingText {
            get {
                return ResourceManager.GetString("UploadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use custom host.
        /// </summary>
        public static string UseCustomHostText {
            get {
                return ResourceManager.GetString("UseCustomHostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} users online.
        /// </summary>
        public static string UsersOnlineText {
            get {
                return ResourceManager.GetString("UsersOnlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting....
        /// </summary>
        public static string WaitingText {
            get {
                return ResourceManager.GetString("WaitingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wordlist.
        /// </summary>
        public static string WordPageTitle {
            get {
                return ResourceManager.GetString("WordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You both like {0}.
        /// </summary>
        public static string YouBothLikeText {
            get {
                return ResourceManager.GetString("YouBothLikeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You disconnected.
        /// </summary>
        public static string YouDisconnectedText {
            get {
                return ResourceManager.GetString("YouDisconnectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string YouText {
            get {
                return ResourceManager.GetString("YouText", resourceCulture);
            }
        }
    }
}
